### ISSUE TITLE
v2.0.0 tag missing

### ISSUE THREAD

**Issue by jedrichards** [neomantra/docker-flatbuffers#1]
I don't seem to be able to find a versioned tag for the [v2.0.0](https://github.com/google/flatbuffers/releases/tag/v2.0.0) release on Docker Hub.

**Comment by neomantra** [comment]
Thanks for letting me know.  I don't use FlatBuffers anymore so haven't been tracking it.

I'll update this once #2 is fixed -- assuming that there is not much major breakage since it built `master`  3 months ago.

**Comment by jedrichards** [comment]
Thank you 🙏

**Comment by neomantra** [comment]
Tag `v2.0.0` and `gcc-v2.0.0-cc0.6.0` is available now.  The clang builds for this tag are not working because of `flatcc` build issues at the tag; `flatcc` master builds.

**Comment by jedrichards** [comment]
Fantastic! Thanks for maintaining this Docker image 🙂

**Comment by neomantra** [comment]
Closing this in favor of more recent #4 .  Thanks!
